// const GENERAL_CAPABILITIES_AND_ID_REGISTER: usize = 0x000;
// const GENERAL_CONFIGURATION_REGISTER: usize = 0x010;
// const GENERAL_INTERRUPT_STATUS_REGISTER: usize = 0x020;
// const MAIN_COUNTER_VALUE_REGISTER: usize = 0x0F0;
// const TIMER_0_CONFIGURATION_AND_CAPABILITY_REGISTER: usize = 0x100;
// const TIMER_0_COMPARATOR_VALUE_REGISTER: usize = 0x108;
// const TIMER_0_FSB_INTERRUPT_ROUTE_REGISTER: usize = 0x110;
